# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release to nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Restore dependencies
      run: dotnet restore
    - name: build solution
      run: dotnet build --configuration Release
    - name: run unit tests
      run: dotnet test
    - name: Create Nuget package
      run: dotnet pack -c Release /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/fjeller/Fjeller.simplemapper/releases/tag/${{ github.event.release.tag_name }}"
    - name: Archive nuget package
      uses: actions/upload-artifact@v4
      with:
        name: Fjeller.SimpleMapper
        path: ./**/Fjeller.SimpleMapper.${{ github.event.release.tag_name }}.nupkg
    - name: Publish nuget Package
      run: dotnet nuget push ./**/Fjeller.SimpleMapper.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols

